#!/bin/bash -e

# Keep track of this script's directory.
cd $(dirname $0)
export DOTFILES_DIR="$(pwd)"

# Import custom functions.
export DOTFILES_LIB="$DOTFILES_DIR/dotfiles_lib"
source $DOTFILES_LIB

# If the user accidentally ran this as root, tell them that this might be wrong.
if [[ "$(id -u)" == "0" ]] ; then
    wecho "You're running as root! Installation will occur in this HOME directory: $HOME"

    # Give the user the option to exit and re-run the script as a non-root
    # user.
    read -p "Do you want to continue running this script as root? [y/n] " yn
    if [[ "$yn" != "y" ]] ; then
        exit 0
    fi
fi


# Install dotfiles configuration file.
export USER_CONFIG_FILE="$DOTFILES_DIR/dotfiles.cfg"
$DOTFILES_DIR/config/install.sh
source $USER_CONFIG_FILE


# Customize terminal installation.
if $CFG_INSTALL_TERMINAL ; then
    iecho "Installing terminal mods"
    $DOTFILES_DIR/terminal/install.sh
fi

# Setup/update Homebrew/Linuxbrew packages.
if $CFG_ENABLE_BREW ; then
    $DOTFILES_DIR/brew/install.sh
fi

# Customize git installation.
if $CFG_INSTALL_GIT ; then
    iecho "Installing git mods"
    $DOTFILES_DIR/git/install.sh
fi

# Customize python installation.
if $CFG_INSTALL_PYTHON_MODS ; then
    iecho "Installing python mods"
    $DOTFILES_DIR/python/install.sh
fi

# Customize tmux installation.
if $CFG_INSTALL_TMUX_MODS ; then
    iecho "Installing tmux mods"
    $DOTFILES_DIR/tmux/install.sh
fi

# Customize neovim installation.
if $CFG_INSTALL_NVIM_MODS ; then
    iecho "Installing neovim mods"
    $DOTFILES_DIR/nvim/install.sh
fi

# Customize zsh installation.
if $CFG_INSTALL_ZSH_MODS ; then
    iecho "Installing zsh"
    $DOTFILES_DIR/zsh/install.sh
fi

# Install/update Rust.
if $CFG_ENABLE_RUST ; then
    $DOTFILES_DIR/rust/install.sh
fi

# Customize scala installation.
if $CFG_INSTALL_SCALA_MODS ; then
    $DOTFILES_DIR/scala/install.sh
fi

# Customize NodeJS installation.
if $CFG_INSTALL_NODE_MODS ; then
    $DOTFILES_DIR/node/install.sh
fi

# Install/update Haskell.
if $CFG_ENABLE_HASKELL ; then
    $DOTFILES_DIR/haskell/install.sh
fi

iecho "Finished!"
