#!/bin/bash -e

# Keep track of this script's directory.
cd $(dirname $0)
export DOTFILES_DIR="$(pwd)"

# Import custom functions.
source $DOTFILES_DIR/dotfiles_lib

# If the user accidentally ran this as root, tell them that this might be wrong.
if [[ "$(id -u)" == "0" ]] ; then
    wecho "You're running as root! Installation will occur in this HOME directory: $HOME"

    # Give the user the option to exit and re-run the script as a non-root
    # user.
    read -p "Do you want to continue running this script as root? [y/n] " yn
    if [[ "$yn" != "y" ]] ; then
        exit 0
    fi
fi


# Setup/update Homebrew/Linuxbrew packages.
$DOTFILES_DIR/brew/install_brew

# Customize git installation.
iecho "Installing git mods"
$DOTFILES_DIR/git/install_git

# Install Base16 Shell.
iecho "Installing Base16 shell"
$DOTFILES_DIR/base16/install_base16

# Install local bin scripts.
iecho "Installing local scripts"
$DOTFILES_DIR/bin/install_bin

# Customize python installation.
iecho "Installing python mods"
$DOTFILES_DIR/python/install_python

# Customize tmux installation.
iecho "Installing tmux mods"
$DOTFILES_DIR/tmux/install_tmux

# Customize vim installation.
iecho "Installing vim mods"
$DOTFILES_DIR/vim/install_vim

# Customize zsh installation.
iecho "Installing zsh"
$DOTFILES_DIR/zsh/install_zsh

iecho "Finished!"
