#!/bin/bash -e

# If a local git repo exists, update it. If it doesn't exist, clone a new repo
# in the expected location.
#
# Inputs:
#   $1 : path to remote git repository to clone/pull.
#   $2 : path to local git repository
git_clone_or_update(){
    if [ -d "$2" ]; then
        echo "Updating $2 from $1"
        cd $2
        git pull
        cd ~
    else
        echo "Cloning $1 into $2"
        git clone $1 $2
    fi
}

# Install vimrc.
VIMRC="$HOME/.vimrc"
if [ ! -e "$VIMRC" ]; then
    ln -s ~/dotfiles/vim/vimrc $VIMRC
fi

# Install flake8 configuration for vim-flake8.
FLAKE8_CONFIG="$HOME/.config/flake8"
if [ ! -e "$FLAKE8_CONFIG" ]; then
    ln -s ~/dotfiles/vim/flake8 $FLAKE8_CONFIG
fi

# Create necessary directories.
VIM_AUTOLOAD="$HOME/.vim/autoload"
VIM_BUNDLE="$HOME/.vim/bundle"
mkdir -p $VIM_AUTOLOAD $VIM_BUNDLE

# Install pathogen. Taken from:
#   https://github.com/tpope/vim-pathogen
curl -LSso "$VIM_AUTOLOAD/pathogen.vim" https://tpo.pe/pathogen.vim

# Lots of customizations taken from:
#   https://realpython.com/blog/python/vim-and-python-a-match-made-in-heaven/

# Syntax checking.
git_clone_or_update https://github.com/scrooloose/syntastic.git \
    "$VIM_BUNDLE/syntastic"

# Awesome status bar.
git_clone_or_update https://github.com/vim-airline/vim-airline.git \
    "$VIM_BUNDLE/vim-airline"

# Themes for awesome status bar.
git_clone_or_update https://github.com/vim-airline/vim-airline-themes.git \
    "$VIM_BUNDLE/vim-airline-themes"

# Column-align multiple lines.
git_clone_or_update https://github.com/junegunn/vim-easy-align.git \
    "$VIM_BUNDLE/vim-easy-align"

# Base16 colors in vim.
git_clone_or_update https://github.com/chriskempson/base16-vim.git \
    "$VIM_BUNDLE/base16-vim"

# Improved ability to save vim sessions to disk.
git_clone_or_update https://github.com/tpope/vim-obsession.git \
    "$VIM_BUNDLE/vim-obsession"

# Allow user-defined text objects (needed for vim-textobj-line).
git_clone_or_update https://github.com/kana/vim-textobj-user.git \
    "$VIM_BUNDLE/vim-textobj-user"

# Make a new text object for the current line.
git_clone_or_update https://github.com/kana/vim-textobj-line.git \
    "$VIM_BUNDLE/vim-textobj-line"

# Make a new text object for lines at the same indent level.
git_clone_or_update https://github.com/michaeljsmith/vim-indent-object.git \
    "$VIM_BUNDLE/vim-indent-object"

# Add new vim "verb" for surrounding text objects.
git_clone_or_update https://github.com/tpope/vim-surround.git \
    "$VIM_BUNDLE/vim-surround"

# Add new vim "verb" for commenting out lines.
git_clone_or_update https://github.com/tpope/vim-commentary.git \
    "$VIM_BUNDLE/vim-commentary"

# Integration for fzf in vim.
git_clone_or_update https://github.com/junegunn/fzf.vim.git \
    "$VIM_BUNDLE/fzf.vim"

# Add ability to easily open new files up to a specific line/column.
git_clone_or_update https://github.com/kopischke/vim-fetch.git \
    "$VIM_BUNDLE/vim-fetch"

# Add ability to use dot operator (.) to repeat plugin map operations.
git_clone_or_update git://github.com/tpope/vim-repeat.git \
    "$VIM_BUNDLE/vim-repeat"
