#!/bin/bash -e

# Install packages for Python3.

# Grab OS-type from inputs.
MAC=$1
CENTOS=$2
UBUNTU=$3

# Install everything needed to:
#   -Build Python code from source
#   -Run Tk GUIs
#   -Install matplotlib
#   -Install numpy
# TODO: Maybe don't need any of this on mac...
if $MAC; then
    brew install python3
elif $CENTOS; then
    echo "No python installs necessary for CentOS."
    exit 0
elif $UBUNTU; then
    sudo apt-get install python3-dev tcl8.6-dev tk8.6-dev tcl-dev tk-dev \
        python3-tk libjpeg-dev libjpeg-turbo8-dev libjpeg8-dev liblcms2-dev \
        libfreetype6-dev libpng12-dev zlib1g-dev libatlas-base-dev gfortran
else
    echo 'No valid operating system specified, exiting.'
    exit 1
fi

# Install inputrc (configuration for readline library) and pystartup.
INPUTRC="$HOME/.inputrc"
PYSTARTUP="$HOME/.pystartup"
if [ ! -e $INPUTRC ]; then
    ln -s -v ~/dotfiles/python/inputrc $INPUTRC
fi
if [ ! -e $PYSTARTUP ]; then
    ln -s -v ~/dotfiles/python/pystartup $PYSTARTUP
fi

# sudo is not necessary on Mac.
if $MAC; then
    INSTALL_CMD="pip3"
elif $UBUNTU; then
    INSTALL_CMD="sudo pip3"
fi

# Install the latest version of pip.
if ! which pip3 >/dev/null 2>&1; then
    if $MAC; then
        echo "pip3 not found, it should be present on Mac platforms. Exiting."
        exit 1
    elif $UBUNTU; then
        # If pip isn't yet installed, then get the newest version.
        curl -O https://bootstrap.pypa.io/get-pip.py
        sudo python3 get-pip.py
        rm get-pip.py
    fi
else
    # If pip is already installed, use it to update itself.
    $INSTALL_CMD install -U pip
fi

# Install all the python packages we want.
$INSTALL_CMD install -U cython
$INSTALL_CMD install -U jupyter
$INSTALL_CMD install -U numpy
$INSTALL_CMD install -U matplotlib
$INSTALL_CMD install -U scipy
$INSTALL_CMD install -U flake8
