#!/bin/bash -e

if [[ -z "$DOTFILES_DIR" ]] ; then
    echo "DOTFILES_DIR is undefined."
    exit 2
fi

# Install packages for Python3.

# Install inputrc (configuration for readline library) and pystartup. This
# should happen regardless of OS.
INPUTRC="$HOME/.inputrc"
PYSTARTUP="$HOME/.pystartup"
if [[ ! -e "$INPUTRC" ]] ; then
    ln -s -v "$DOTFILES_DIR/python/inputrc" "$INPUTRC"
fi
if [[ ! -e "$PYSTARTUP" ]] ; then
    ln -s -v "$DOTFILES_DIR/python/pystartup" "$PYSTARTUP"
fi

# Grab OS-type from inputs.
MAC=$1
CENTOS=$2
UBUNTU=$3

# Install everything needed to:
#   -Build Python code from source
#   -Run Tk GUIs
#   -Install matplotlib
#   -Install numpy
# TODO: Maybe don't need any of this on mac...
if $MAC; then
    if ! command -v python3 >/dev/null 2>&1; then
        brew install python3
    fi
elif $CENTOS; then
    echo "No python installs necessary for CentOS."
    exit 0
elif $UBUNTU; then
    sudo apt-get install python3-dev tcl8.6-dev tk8.6-dev tcl-dev tk-dev \
        python3-tk libjpeg-dev libjpeg-turbo8-dev libjpeg8-dev liblcms2-dev \
        libfreetype6-dev libpng12-dev zlib1g-dev libatlas-base-dev gfortran
else
    echo 'No valid operating system specified, exiting.'
    exit 1
fi

# sudo is not necessary on Mac.
if $MAC; then
    INSTALL_CMD="pip3"
elif $UBUNTU; then
    INSTALL_CMD="sudo pip3"
fi

# Install the latest version of pip.
if ! which pip3 >/dev/null 2>&1; then
    if $MAC; then
        echo "pip3 not found, it should be present on Mac platforms. Exiting."
        exit 1
    elif $UBUNTU; then
        # If pip isn't yet installed, then get the newest version.
        curl -O https://bootstrap.pypa.io/get-pip.py
        sudo python3 get-pip.py
        rm get-pip.py
    fi
else
    # If pip is already installed, use it to update itself.
    $INSTALL_CMD install --upgrade pip
fi

# Install all the python packages we want.
$INSTALL_CMD install --upgrade \
    jupyter \
    jupyterlab \
    numpy \
    matplotlib \
    scipy \
    flake8
