#!/bin/bash -e

# Customize tmux installation.

if [[ -z "$DOTFILES_DIR" ]] ; then
    echo "DOTFILES_DIR is undefined."
    exit 2
fi


TMUX_CONF="$HOME/.tmux.conf"
if [[ ! -e "$TMUX_CONF" ]] ; then
    ln -s -v "$DOTFILES_DIR/tmux/tmux.conf" "$TMUX_CONF"
fi

# Install Tmux Plugin Manager
TPM_DIR="$HOME/.tmux/plugins/tpm"
if [[ ! -e "TPM_DIR" ]] ; then
    git clone https://github.com/tmux-plugins/tpm "$TPM_DIR"
fi
