# TODO: Place the time on the right side. Some inspiration:
#   ~/.zprezto/modules/prompt/external master !2 ─────────────────────────── 5s ≡ 17:43:00
#   ❯

[directory]
truncation_length = 8

[jobs]
# symbol = "≡"
threshold = 0

[time]
disabled = false

[git_status]
conflicted_count.enabled = true
modified_count.enabled = true
staged_count.enabled = true
show_sync_count = true
