# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="powerlevel10k/powerlevel10k"

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# Caution: this setting can cause issues with multiline prompts (zsh 5.7.1 and newer seem to work)
# See https://github.com/ohmyzsh/ohmyzsh/issues/5765
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
HIST_STAMPS="yyyy-mm-dd"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Increase size of ZSH command history
export HISTSIZE=100000
export SAVEHIST=100000

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=( \
  vi-mode \
)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Don't share history between all sessions
unsetopt SHARE_HISTORY

# Report the status of background and suspended jobs before exiting
setopt CHECK_JOBS

# Shorten the transition from vi-insert to vi-normal mode (this variable is in
# units of milliseconds)
export KEYTIMEOUT=1

# Load system-specific modifications to the shell
[[ -f "$HOME/.zshrc.local" ]] && source "$HOME/.zshrc.local"

# Add Scala tools to PATH
export COURSIER_BIN_DIR="$HOME/.local/share/coursier/bin"
[[ -d "$COURSIER_BIN_DIR" ]] && path=("$COURSIER_BIN_DIR" $path)
[[ -s "${SDKMAN_DIR:-$HOME/.sdkman}/bin/sdkman-init.sh" ]] && source "${SDKMAN_DIR:-$HOME/.sdkman}/bin/sdkman-init.sh"

# Add Haskell tools to PATH
[[ -f "${GHCUP_INSTALL_BASE_PREFIX:-$HOME}/.ghcup/env" ]] && source "${GHCUP_INSTALL_BASE_PREFIX:-$HOME}/.ghcup/env"

# Add Rust toolchain to PATH
[[ -f ~/.cargo/env ]] && source ~/.cargo/env

# Customize PATH
path=(
  ~/.local/bin
  $path
)

# Load Homebrew path/environment modifications.
command -v brew > /dev/null 2>&1 && eval $(brew shellenv)

if [[ -n "$HOMEBREW_PREFIX" ]]; then
  # If LLVM is installed, add all of the LLVM utilities to the end of the path.
  [[ -d "$HOMEBREW_PREFIX/opt/llvm/bin" ]] && path=($path "$HOMEBREW_PREFIX/opt/llvm/bin")

  # If ruby is installed, add to the start of the path, to override the
  # OS-provided version.
  [[ -d "$HOMEBREW_PREFIX/opt/ruby/bin" ]] && path=("$HOMEBREW_PREFIX/opt/ruby/bin" $path)
  [[ -d "$HOMEBREW_PREFIX/lib/ruby/gems/3.2.0/bin" ]] && path=("$HOMEBREW_PREFIX/lib/ruby/gems/3.2.0/bin" $path)

  # If 'make' is installed, add it to the start of the path, so we can use more
  # modern 'make' features.
  [[ -d "$HOMEBREW_PREFIX/opt/make/libexec/gnubin" ]] && path=("$HOMEBREW_PREFIX/opt/make/libexec/gnubin" $path)
fi

# Set up modifications for Python REPL
[[ -f "$HOME/.pystartup" ]] && export PYTHONSTARTUP="$HOME/.pystartup"

# Set up git aliases
[[ -f "$HOME/.config/git.zsh" ]] && source "$HOME/.config/git.zsh"

# Configure line editor
[[ -f "$HOME/.config/editor.zsh" ]] && source "$HOME/.config/editor.zsh"

# Set up default text editor
if command -v nvim > /dev/null 2>&1 ; then
  alias vim="nvim"
  alias vimdiff="nvim -d"
  export EDITOR="nvim"
  export VISUAL="nvim"
else
  export EDITOR="vim"
  export VISUAL="vim"
fi

export PAGER="less"

# Customize 'less' options
export LESS="-i -M -R -S -w -X -z-4"

# Replace ls with exa
if command -v exa > /dev/null 2>&1 ; then
  alias exa="exa --classify"
  alias ls="exa"
  alias ll="ls --long --binary --group --icons"
  alias llg="ll --git"
  alias la="ll --all"
  alias l="ls --oneline --all"
  alias lr="ls --recurse"
  alias llr="ll --recurse"
  alias lt="ls --tree"
  alias llt="ll --tree"
  alias llst="ll --sort=newest" # Sort by modified time, most recent at the bottom
  alias llss="ll --sort=size"   # Sort by size, largest at the bottom

  # 'git status' in tree view
  alias gwst="exa -l --tree --git --git-ignore \
    --no-filesize --no-permissions --no-user --no-time --color=always \
    | awk '\$1 !~ /--/ { print }'"
fi

# Set up fzf
[ -f ~/.fzf.zsh ] && [[ -f "$HOME/.config/fzf-config.zsh" ]] && source "$HOME/.config/fzf-config.zsh"

# Set up shell prompt
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Set up wezterm shell integration
function {
  local wezterm_shell_int_macos="/Applications/WezTerm.app/Contents/Resources/wezterm.sh"
  [[ -f "$wezterm_shell_int_macos" ]] && source "$wezterm_shell_int_macos"
}
