#!/bin/sh

# Update ctags for a git repo.
# To be invoked by other git hooks.
# Source: https://tbaggery.com/2011/08/08/effortless-ctags-with-git.html

set -e
PATH="/usr/local/bin:$PATH"
dir="`git rev-parse --git-dir`"
trap 'rm -f "$dir/$$.tags"' EXIT
git ls-files --recurse-submodules | \
    ctags --tag-relative -L - -f"$dir/$$.tags"
mv "$dir/$$.tags" "$dir/tags"
